const MEI_TUAN_COOKIES = [
  {
      "domain": ".i.meituan.com",
      "expirationDate": 1732342955.057116,
      "hostOnly": false,
      "httpOnly": false,
      "name": "__mta",
      "path": "/s",
      "sameSite": "unspecified",
      "secure": false,
      "session": false,
      "storeId": "0",
      "value": "209033773.1697782761667.1697782761667.1697782955057.2",
      "id": 1
  },
  {
      "domain": ".meituan.com",
      "expirationDate": 1732342955.320597,
      "hostOnly": false,
      "httpOnly": false,
      "name": "__utma",
      "path": "/",
      "sameSite": "unspecified",
      "secure": false,
      "session": false,
      "storeId": "0",
      "value": "74597006.1094169763.1697782115.1697782115.1697782115.1",
      "id": 2
  },
  {
      "domain": ".meituan.com",
      "expirationDate": 1697784755,
      "hostOnly": false,
      "httpOnly": false,
      "name": "__utmb",
      "path": "/",
      "sameSite": "unspecified",
      "secure": false,
      "session": false,
      "storeId": "0",
      "value": "74597006.11.9.1697782865722",
      "id": 3
  },
  {
      "domain": ".meituan.com",
      "hostOnly": false,
      "httpOnly": false,
      "name": "__utmc",
      "path": "/",
      "sameSite": "unspecified",
      "secure": false,
      "session": true,
      "storeId": "0",
      "value": "74597006",
      "id": 4
  },
  {
      "domain": ".meituan.com",
      "expirationDate": 1713550955,
      "hostOnly": false,
      "httpOnly": false,
      "name": "__utmz",
      "path": "/",
      "sameSite": "unspecified",
      "secure": false,
      "session": false,
      "storeId": "0",
      "value": "74597006.1697782115.1.1.utmcsr=(direct)|utmccn=(direct)|utmcmd=(none)",
      "id": 5
  },
  {
      "domain": ".meituan.com",
      "expirationDate": 1698387309,
      "hostOnly": false,
      "httpOnly": false,
      "name": "_lx_utm",
      "path": "/",
      "sameSite": "unspecified",
      "secure": false,
      "session": false,
      "storeId": "0",
      "value": "utm_source%3Dgoogle%26utm_medium%3Dorganic",
      "id": 6
  },
  {
      "domain": ".meituan.com",
      "expirationDate": 1732342034.697194,
      "hostOnly": false,
      "httpOnly": false,
      "name": "_lxsdk",
      "path": "/",
      "sameSite": "unspecified",
      "secure": false,
      "session": false,
      "storeId": "0",
      "value": "BF1686D9BE1C734F5A53543100FFD8ECECCBBC57CA3B740B5A6448CC65F8FE8C",
      "id": 7
  },
  {
      "domain": ".meituan.com",
      "expirationDate": 1732334184.644472,
      "hostOnly": false,
      "httpOnly": false,
      "name": "_lxsdk_cuid",
      "path": "/",
      "sameSite": "unspecified",
      "secure": false,
      "session": false,
      "storeId": "0",
      "value": "17e8b4ea3f3c8-0bf733e98a153b-2363163-384000-17e8b4ea3f3c8",
      "id": 8
  },
  {
      "domain": ".meituan.com",
      "expirationDate": 1697784754,
      "hostOnly": false,
      "httpOnly": false,
      "name": "_lxsdk_s",
      "path": "/",
      "sameSite": "unspecified",
      "secure": false,
      "session": false,
      "storeId": "0",
      "value": "18b4bb1c2ab-6cd-88f-e97%7C%7C148",
      "id": 9
  },
  {
      "domain": ".meituan.com",
      "expirationDate": 1732342954.408165,
      "hostOnly": false,
      "httpOnly": false,
      "name": "ci",
      "path": "/",
      "sameSite": "unspecified",
      "secure": false,
      "session": false,
      "storeId": "0",
      "value": "30",
      "id": 10
  },
  {
      "domain": ".meituan.com",
      "hostOnly": false,
      "httpOnly": false,
      "name": "ci3",
      "path": "/",
      "sameSite": "unspecified",
      "secure": false,
      "session": true,
      "storeId": "0",
      "value": "65",
      "id": 11
  },
  {
      "domain": ".meituan.com",
      "expirationDate": 1732342954.408175,
      "hostOnly": false,
      "httpOnly": false,
      "name": "cityname",
      "path": "/",
      "sameSite": "unspecified",
      "secure": false,
      "session": false,
      "storeId": "0",
      "value": "%E6%B7%B1%E5%9C%B3",
      "id": 12
  },
  {
      "domain": ".meituan.com",
      "expirationDate": 1729318955,
      "hostOnly": false,
      "httpOnly": false,
      "name": "i_extend",
      "path": "/",
      "sameSite": "unspecified",
      "secure": false,
      "session": false,
      "storeId": "0",
      "value": "C_b0H__a100005__b1",
      "id": 13
  },
  {
      "domain": ".meituan.com",
      "expirationDate": 1697786361,
      "hostOnly": false,
      "httpOnly": false,
      "name": "idau",
      "path": "/",
      "sameSite": "unspecified",
      "secure": false,
      "session": false,
      "storeId": "0",
      "value": "1",
      "id": 14
  },
  {
      "domain": ".meituan.com",
      "hostOnly": false,
      "httpOnly": false,
      "name": "IJSESSIONID",
      "path": "/",
      "sameSite": "unspecified",
      "secure": false,
      "session": true,
      "storeId": "0",
      "value": "node0ca8jxbf7qx5v1jxnevrcy9u271618626",
      "id": 15
  },
  {
      "domain": ".meituan.com",
      "expirationDate": 1703041201.262923,
      "hostOnly": false,
      "httpOnly": true,
      "name": "isid",
      "path": "/",
      "sameSite": "unspecified",
      "secure": false,
      "session": false,
      "storeId": "0",
      "value": "AgFaJLQmxjSKrIZ1ssAbARJOZxYFFfqpBGB5Zd3oIDb-UrcgfaxxO56fjJSsXq1Q1MiKYIKMFVPHhAAAAAB5GwAARxLmusMixMgBJ1KaRBmpxbFlYh9L_2tx-PrSsVzHl9veD01lq7ld6PLhhhoJg5OE",
      "id": 16
  },
  {
      "domain": ".meituan.com",
      "expirationDate": 1732342760.722387,
      "hostOnly": false,
      "httpOnly": false,
      "name": "iuuid",
      "path": "/",
      "sameSite": "unspecified",
      "secure": false,
      "session": false,
      "storeId": "0",
      "value": "BF1686D9BE1C734F5A53543100FFD8ECECCBBC57CA3B740B5A6448CC65F8FE8C",
      "id": 17
  },
  {
      "domain": ".meituan.com",
      "expirationDate": 1698387667,
      "hostOnly": false,
      "httpOnly": false,
      "name": "latlng",
      "path": "/",
      "sameSite": "unspecified",
      "secure": false,
      "session": false,
      "storeId": "0",
      "value": "22.319303,114.169361,1697782867143",
      "id": 18
  },
  {
      "domain": ".meituan.com",
      "expirationDate": 1703041201.262995,
      "hostOnly": false,
      "httpOnly": false,
      "name": "logintype",
      "path": "/",
      "sameSite": "unspecified",
      "secure": false,
      "session": false,
      "storeId": "0",
      "value": "normal",
      "id": 19
  },
  {
      "domain": ".meituan.com",
      "expirationDate": 1703041201.262974,
      "hostOnly": false,
      "httpOnly": false,
      "name": "mt_c_token",
      "path": "/",
      "sameSite": "unspecified",
      "secure": false,
      "session": false,
      "storeId": "0",
      "value": "AgFaJLQmxjSKrIZ1ssAbARJOZxYFFfqpBGB5Zd3oIDb-UrcgfaxxO56fjJSsXq1Q1MiKYIKMFVPHhAAAAAB5GwAARxLmusMixMgBJ1KaRBmpxbFlYh9L_2tx-PrSsVzHl9veD01lq7ld6PLhhhoJg5OE",
      "id": 20
  },
  {
      "domain": ".meituan.com",
      "hostOnly": false,
      "httpOnly": false,
      "name": "oops",
      "path": "/",
      "sameSite": "unspecified",
      "secure": false,
      "session": true,
      "storeId": "0",
      "value": "AgFaJLQmxjSKrIZ1ssAbARJOZxYFFfqpBGB5Zd3oIDb-UrcgfaxxO56fjJSsXq1Q1MiKYIKMFVPHhAAAAAB5GwAARxLmusMixMgBJ1KaRBmpxbFlYh9L_2tx-PrSsVzHl9veD01lq7ld6PLhhhoJg5OE",
      "id": 21
  },
  {
      "domain": ".meituan.com",
      "expirationDate": 1728886354,
      "hostOnly": false,
      "httpOnly": false,
      "name": "pinyin",
      "path": "/",
      "sameSite": "unspecified",
      "secure": false,
      "session": false,
      "storeId": "0",
      "value": "shenzhen",
      "id": 22
  },
  {
      "domain": ".meituan.com",
      "expirationDate": 1713334760.720919,
      "hostOnly": false,
      "httpOnly": true,
      "name": "token",
      "path": "/",
      "sameSite": "unspecified",
      "secure": false,
      "session": false,
      "storeId": "0",
      "value": "AgFaJLQmxjSKrIZ1ssAbARJOZxYFFfqpBGB5Zd3oIDb-UrcgfaxxO56fjJSsXq1Q1MiKYIKMFVPHhAAAAAB5GwAARxLmusMixMgBJ1KaRBmpxbFlYh9L_2tx-PrSsVzHl9veD01lq7ld6PLhhhoJg5OE",
      "id": 23
  },
  {
      "domain": ".meituan.com",
      "hostOnly": false,
      "httpOnly": false,
      "name": "u",
      "path": "/",
      "sameSite": "unspecified",
      "secure": false,
      "session": true,
      "storeId": "0",
      "value": "499004639",
      "id": 24
  },
  {
      "domain": ".meituan.com",
      "expirationDate": 1713334760.817096,
      "hostOnly": false,
      "httpOnly": false,
      "name": "userId",
      "path": "/",
      "sameSite": "unspecified",
      "secure": false,
      "session": false,
      "storeId": "0",
      "value": "499004639",
      "id": 25
  },
  {
      "domain": ".meituan.com",
      "expirationDate": 1732342035.084302,
      "hostOnly": false,
      "httpOnly": true,
      "name": "uuid",
      "path": "/",
      "sameSite": "unspecified",
      "secure": false,
      "session": false,
      "storeId": "0",
      "value": "3fb6ebacc7924de184c7.1697782035.1.0.0",
      "id": 26
  },
  {
      "domain": ".meituan.com",
      "expirationDate": 1732342531.245281,
      "hostOnly": false,
      "httpOnly": false,
      "name": "WEBDFPID",
      "path": "/",
      "sameSite": "unspecified",
      "secure": false,
      "session": false,
      "storeId": "0",
      "value": "wy4855y56889535z00946w124481v08w81y5y622w3697958y989w64u-2013134009698-1697774009698OESYMUIfd79fef3d01d5e9aadc18ccd4d0c95079092",
      "id": 27
  },
  {
      "domain": ".meituan.com",
      "expirationDate": 1729318954,
      "hostOnly": false,
      "httpOnly": false,
      "name": "webp",
      "path": "/",
      "sameSite": "unspecified",
      "secure": false,
      "session": false,
      "storeId": "0",
      "value": "1",
      "id": 28
  },
  {
      "domain": "i.meituan.com",
      "hostOnly": true,
      "httpOnly": false,
      "name": "JSESSIONID",
      "path": "/",
      "sameSite": "unspecified",
      "secure": false,
      "session": true,
      "storeId": "0",
      "value": "node0ca8jxbf7qx5v1jxnevrcy9u271618626.node0",
      "id": 29
  },
  {
      "domain": "i.meituan.com",
      "hostOnly": true,
      "httpOnly": false,
      "name": "logan_session_token",
      "path": "/",
      "sameSite": "unspecified",
      "secure": false,
      "session": true,
      "storeId": "0",
      "value": "y6e0q56ocvyy4k224vad",
      "id": 30
  },
  {
      "domain": "i.meituan.com",
      "expirationDate": 1697783166.417652,
      "hostOnly": true,
      "httpOnly": false,
      "name": "webloc_geo",
      "path": "/",
      "sameSite": "unspecified",
      "secure": false,
      "session": false,
      "storeId": "0",
      "value": "22.319303%2C114.169361%2Cwgs84%2C20198.511783027254",
      "id": 31
  }
  ]

  module.exports = { MEI_TUAN_COOKIES }